---
- name: Ensure package updates
  ansible.builtin.package:
    name: "*"
    state: latest # noqa package-latest

- name: Install basic packages
  ansible.builtin.package:
    name:
      - "git"
      - "vim"
      - "curl"
    state: present
