name: "Lint Ansible files"

on: [ push, pull_request ]

jobs:
  lint:
    name: "Lint files"
    uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
    with:
      args: '-p inventories playbooks roles'  # Directory
