name: "Ansible Deployment"

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ terraform-deployed ]

jobs:
  aws-ansible:
    name: "AWS Deployment"
    uses: ./.github/workflows/aws-ansible.yml
    permissions:
      contents: read
    secrets: inherit
    with:
      environment: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.environment || inputs.environment }}
  azure-ansible:
    name: "Azure Deployment"
    uses: ./.github/workflows/azure-ansible.yml
    permissions:
      contents: read
      id-token: write
    secrets: inherit
    with:
      environment: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.environment || inputs.environment }}
  gcp-ansible:
    name: "GCP Deployment"
    uses: ./.github/workflows/gcp-ansible.yml
    permissions:
      contents: read
      id-token: write
    secrets: inherit
    with:
      environment: ${{ github.event_name == 'repository_dispatch' && github.event.client_payload.environment || inputs.environment }}
